name: Publish Olive Packages

on:
  push:
    branches: [ generalize-publish-action ]

jobs:
 build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

     # This step will create "an array" of strings, e.g. "path1 path2 path3"
    - name: array
      id: arr
      run: |
        arr=()
        for i in "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
        do
          if [[ $i == *"path1"* ]]; then
            arr+=("path1")
          fi
          if [[ $i == *"path2"* ]]; then
            arr+=("path2")
          fi
        done
        echo ::set-output name=arr::${arr[@]}
   
 #   - name: Publish Olive NuGet Package
 #     uses: brandedoutcast/publish-nuget@v2
 #     with:
 #       PROJECT_FILE_PATH: Olive/Olive.csproj
 #       NUGET_KEY: ${{secrets.NUGET_API_KEY}}