name: Publish Olive Packages

on:
  push:
    branches: [ generalize-publish-action ]

jobs:
 build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: array
      id: arr
      run: |
        git diff --name-only HEAD~1 --diff-filter=AMDR
   
 #   - name: Publish Olive NuGet Package
 #     uses: brandedoutcast/publish-nuget@v2
 #     with:
 #       PROJECT_FILE_PATH: Olive/Olive.csproj
 #       NUGET_KEY: ${{secrets.NUGET_API_KEY}}